### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by Keith94** [SeanPesce/Dark_Souls_Config_Utility#2]
`make.bat` gives an error:

>'javac' is not recognized as an internal or external command, operable program or batch file.

**Comment by SeanPesce** [comment]
Hi Keith, thanks for the feedback!  

To compile this project with `make_all.bat`:  
* [Install the JDK](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html)  
* Add the JDK install directory to your %PATH% environment variable (See below for instructions)  
* Install [Inno Setup](http://www.jrsoftware.org/isdl.php)   
* Add the Inno Setup install directory to your %PATH% (See below)  
* If your JDK is installed somewhere other than `C:\Program Files\Java\jdk1.8.0_121`, you'll need to edit line 33 of `make.bat` with your JDK directory (I'll try to update this script to be more universal at some point).  
  
  
  
You can add to your %PATH% by going to Start**→**Edit the System Environment Variables→Advanced tab→Environment Variables→select "Path"→Edit→New→paste the program directory→OK  
  
  **OR**  
  
Download **[this](https://github.com/SeanPesce/Dark_Souls_Config_Utility/files/884077/Script.-.Add.to.PATH.variable.zip)**\* batch/Powershell script, which will prompt you for the directory and add it to your %PATH% automatically (run **`_add_to_user_path.bat`**). You might need administrative access for it to work.  
  
# **\*Disclaimer: These scripts let you add anything to your %PATH%, so be careful. By downloading and running them you are agreeing not to hold me accountable for any misuse.**  


If you want to know what the directories look like, my JDK directory is:  
* `C:\Program Files\Java\jdk1.8.0_121\bin` (note that I included the "\\bin" folder)  

My Inno Setup directory is:  
* `C:\Program Files (x86)\Inno Setup 5`    
  
I'll be adding all this info (and more) to the Readme when I get the chance. Also, I'll be uploading a build sometime tonight or in the next few days, so you won't have to do any compilation. Let me know if you have any other issues!

**Comment by SeanPesce** [comment]
Additionally, please close this issue if you get it working (or if you no longer care about getting it working). Thanks!

**Comment by Keith94** [comment]
Well, if you will add a build for it, I can wait for that instead. But thanks for the info.
